apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:DxR1Zi4b1a/7qY6yAbOL9nI0081aIppL,iv:wter9zWXdt/12VKFA66YlL3mW2W+05gaoCmeQJ03Js0=,tag:w7X5nstyKcl9u3uWnq3yjw==,type:str]
    api-key: ENC[AES256_GCM,data:5z7KExTLZY1XmD90yYpoN7nrt85SD4Z2FD/qbo09/Mi2m44WCg==,iv:XROuLZlJAc79OH1mXEJae/A0alH9ATgHyuK7r1KO4Ls=,tag:F3VARWTuzJ5vRXSBlmDDKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hr7esfhm4f3x7swycpes27jkjcqtxnwzu2dxe4fe5dgk6nelusrqnpk3gv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuK0lqa0FFaDRxbUpNK2lB
            MUFOS3hqSzZBeW95dWVCa1JGWWpJMTNiMVd3CjRDdGhzcUNwcWY5aWdEVklxa2VF
            SFNZejV3UEI0ZFlkbHJQQmlNSVc5bjAKLS0tIExzd1YrZjlDRDVXTndUQVBDaXJh
            T25CaGZ4ejJ3Zm92SC9qVU4zdXBpT2sKRW2HHXXmWwIoAvDnRNKjmBKyRbCrFCVa
            6NsYU6M/s+Crj/2t/p1W5cdSTQXwMm/5ah0ck3cWyag06+3oKI/87w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-28T15:49:27Z"
    mac: ENC[AES256_GCM,data:nmwf6N9pLVATH9RusQIIgBf3qw06LTkqOxpegE4F4dNUZOpPX8ZJ7UJd89o5yH73xXlr/dmFdKCh7q+GVJEVAIFmqZFB9S0/dQ2wY0mX4EypM1yEdoZAJcVgtnffnMSNtwLVeMIbItJkIWzG6uiGIAv4EsTKKnK+k9mXH+1pRdM=,iv:qT2OS9GAKfIFWibsK1HXY89MgiSkxM9t8HYoj7SZgkI=,tag:nJ9xxo6/Gu6oJjpmxmrLvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
