---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Oslo"
  KUBE_VIP_ADDR: "10.0.102.250"
  METALLB_LB_RANGE: "10.0.102.170-10.0.102.180"
  METALLB_K8S_GATEWAY_ADDR: "10.0.102.170"
  METALLB_INGRESS_ADDR: "10.0.102.171"
